export const sliderData = [
    {
        title: 'First real estate',
        image: require('../assets/bds1.jpg'),
    },
    {
        title: 'Second real estate',
        image: require('../assets/bds2.jpg'),
    },
    {
        title: 'Third real estate',
        image: require('../assets/bds3.jpg'),
    },

];

export const Projectland = [
    {
       poster: require('../assets/1a.jpg'),
       title: 'Flower-PenHouse',
       subtitle: 'DaLat City',
       isFree: 'No',
       price: '$300',
       id: 1,
    },
    {
       poster: require('../assets/2a.jpg'),
       title: 'Wood-PenHouse',
       subtitle: 'SaPa City',
       isFree: 'No',
       price: '$400',
       id: 2,
    },
    {
       poster: require('../assets/3a.jpg'),
       title: 'PenHouse',
       subtitle: 'DaLat City',
       isFree: 'No',
       price: '$500',
       id: 3,
    },
    {
       poster: require('../assets/4a.jpg'),
       title: 'Smart-Home',
       subtitle: 'QuyNhon City',
       isFree: 'No',
       price: '$600',
       id: 4,
    },
    {
       poster: require('../assets/5a.jpg'),
       title: 'Lake-PenHoue',
       subtitle: 'HaNoi City',
       isFree: 'No',
       price: '$700',
       id: 5,
    },
    {
       poster: require('../assets/6a.jpg'),
       title: 'Smart-PenHouse',
       subtitle: 'DaNang City',
       isFree: 'No',
       price: '$800',
       id: 6,
    },
];

export const apartment = [
    { poster: require('../assets/z.jpg'),
       title: 'Century',
       subtitle: 'DaNang City',
       isFree: 'Yes',
       id: 1,
    },
    { poster: require('../assets/x.jpg'),
       title: 'Victoria',
       subtitle: 'QuyNhon City',
       isFree: 'Yes',
       id: 2,
    },
    { poster: require('../assets/c.jpg'),
       title: 'Kategori',
       subtitle: 'NhaTrang City',
       isFree: 'Yes',
       id: 3,
    },
    { poster: require('../assets/v.jpg'),
       title: 'WOLF',
       subtitle: 'DaNang City',
       isFree: 'Yes',
       id: 4,
    },
    { poster: require('../assets/n.jpg'),
       title: 'Leon',
       subtitle: 'DaNang City',
       isFree: 'Yes',
       id: 5,
    },
    { poster: require('../assets/m.jpg'),
       title: 'Sky',
       subtitle: 'HaNoi City',
       isFree: 'Yes',
       id: 6,
    },

];

